### ISSUE TITLE
[Task] GitHub Actions Workflow Setup

### ISSUE THREAD

**Issue by ogoldberg** [ogoldberg/exit-project-board#7]
## Objective
Set up comprehensive GitHub Actions workflows for CI/CD, including build, test, and deployment automation.

## Tasks
1. Flutter CI Workflow:
```yaml
name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .
    
    - name: Analyze project source
      run: flutter analyze
    
    - name: Run tests
      run: flutter test --coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    
  build-android:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
    - run: flutter pub get
    - run: flutter build apk
    - uses: actions/upload-artifact@v3
      with:
        name: android-build
        path: build/app/outputs/flutter-apk/app-release.apk
    
  build-ios:
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
```

2. Documentation Workflow:
```yaml
name: Documentation

on:
  push:
    branches: [ main ]
    paths:
    - 'docs/**'
    - '**.md'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: |
        npm install -g @docusaurus/core @docusaurus/preset-classic
    - name: Build documentation
      run: |
        cd docs
        npm install
        npm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
```

3. Release Workflow:
```yaml
name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
```

## Success Criteria
- All workflows running successfully
- Tests passing on all PRs
- Documentation auto-deploying
- Releases automated
- Build artifacts properly uploaded

## Dependencies
- None (this is a foundational task)

## Priority
High

## Estimated Time
1 day
